### PR TITLE
Emergencydetails

### PR DESCRIPTION
**Pull request by SriramPatibanda**
Added emergency details view and slide up feature.

### CODE REVIEW

**Comment by adithyaanilkumar** [comment]
give @SriramPatibanda 150 points

**Comment by adithyaanilkumar** [comment]
give @SriramPatibanda 150 points

**Comment by abhinavraj23** [comment]
@adithyaanilkumar I think this should be assigned 75 points, any justification for 150 points?

**Comment by adithyaanilkumar** [comment]
@abhinavraj23 As per the effort put in by the participant in trying to find the best approach to get the slider component, i decided to award him with 150 points. We had lots of discussions on how we would be able to achieve this feature and the participant has put in his entire efforts to make this PR. He deserves this 150 points.

**Comment by abhinavraj23** [comment]
@adithyaanilkumar In order to have a normalized score I think this length PR should be given at max 75 points, thus we have decided upon reducing it to 75.

**Pull request merged**
