### PR TITLE
Added 404 Page and created some necessary scripts

### PR DESCRIPTION
**Pull request by Ashray11**
Added components folder consisting of 404 Error Page and changed scripts including nodemon and concurrently to run react and backend simultaneously.

### CODE REVIEW

**Comment by Ashray11** [comment]
Please check whether it is good enough or not and I would like you to look at issue occuring in importing gsap module in index.js file of public.

**Comment by adithyaanilkumar** [comment]
I will definitely look into it

**Comment by abhinavraj23** [comment]
No points for this PR @adithyaanilkumar ? Any reason? Atleast 5 points can be given.

**Comment by adithyaanilkumar** [comment]
give @Ashray11 25 points

**Pull request merged**
