### PR TITLE
Home view

### PR DESCRIPTION
**Pull request by SriramPatibanda**
Added HomeView which presently contains a bottom Navigation bar with 2 pages namely home and profile. The profile page needs to be updated with user details and the homeview contains a mapbox street map. Some debugging needs to be done to show the accurate location of the user.

### CODE REVIEW

**Comment by adithyaanilkumar** [comment]
Great work ! If you could attach an apk , it would be great!

**Comment by adithyaanilkumar** [comment]
give @SriramPatibanda 150 points

**Comment by SriramPatibanda** [comment]
> Great work ! If you could attach an apk , it would be great!

Yeah sure

**Comment by adithyaanilkumar** [comment]
give @SriramPatibanda 75 points

**Pull request merged**
